#!/usr/bin/env node
'use strict';
// Sprint 6 human-review generator — produces the five itineraries the sprint
// asks to be reviewed by a person (Adventure/Calm/Romantic/Budget/Creative),
// using the REAL pipeline against the extended dense-capital fixture (the
// only fixture with the new Sprint 6 discovery categories). Run with:
//   node tests/generateFiveItineraries.js
// Writes to: docs/product/sprint6-five-itinerary-review.md

const fs = require('node:fs');
const path = require('node:path');
const { loadDecisionEngine } = require('./loadDecisionEngine.js');
const { ENVIRONMENTS } = require('./fixtures/environments.js');
const { runScenario } = require('./scenarioRunner.js');

const OUTPUT_PATH = path.join(__dirname, '..', 'docs', 'product', 'sprint6-five-itinerary-review.md');

const FIVE_SCENARIOS = {
  adventure:  { label: 'Adventure',  vibe: 'adventurous', group: 'friends', budget: 2, weatherKey: 'clear',      durationHours: 7, startMin: 10*60 },
  calm:       { label: 'Calm',       vibe: 'chill',       group: 'solo',    budget: 2, weatherKey: 'clear',      durationHours: 7, startMin: 10*60 },
  romantic:   { label: 'Romantic',   vibe: 'romantic',    group: 'couple',  budget: 2, weatherKey: 'clear',      durationHours: 5, startMin: 17*60 },
  budget:     { label: 'Budget',     vibe: 'budget',      group: 'couple',  budget: 1, weatherKey: 'clear',      durationHours: 7, startMin: 10*60 },
  creative:   { label: 'Creative',   vibe: 'creative',    group: 'solo',    budget: 2, weatherKey: 'clear',      durationHours: 7, startMin: 10*60 },
};

function fmtStop(s, i){
  const dur = s.end - s.start;
  const dist = s.distFromPrev != null ? s.distFromPrev.toFixed(2)+'km' : '(first stop)';
  return `${i+1}. **${s.poi.tags.name}** (${s.poi.category}) — tier: \`${s.tierUsed}\`, ${dur}min, ${dist} from previous`;
}

function main(){
  const eng = loadDecisionEngine();
  const environment = ENVIRONMENTS.denseCapital;
  let out = `# Sprint 6 — Five-Itinerary Human Review\n\nGenerated by \`tests/generateFiveItineraries.js\` against the dense-capital fixture (extended with Sprint 6 discovery categories). Regenerate with:\n\`\`\`\nnode tests/generateFiveItineraries.js\n\`\`\`\n\nThis is the raw material for the required Sprint 6 human review — weak stops, repeated categories, generic explanations, boring discoveries, unrealistic costs, and missing opening hours were checked against this actual output, not assumed. See the "Review findings" section at the end.\n\n---\n\n`;

  for(const [key, scenario] of Object.entries(FIVE_SCENARIOS)){
    const result = runScenario(eng, 'denseCapital', environment, { ...scenario, __key: key });
    const { stops, dayTrace, explanation, profile } = result;
    const cost = eng.estimateDailyCost(stops, scenario.budget, environment.center);
    const fmt = eng.formatCostEstimate(cost);
    const touches = eng.buildOptionalTouches(stops, environment.pois, environment.center);

    out += `## ${scenario.label}\n\n`;
    out += `- Vibe: \`${scenario.vibe}\` · Group: \`${scenario.group}\` · Budget: \`${scenario.budget}\` · Pace: ${profile.pace}\n`;
    out += `- Density tier: ${dayTrace.densityTier}\n\n`;
    out += `**Stops (${stops.length}):**\n`;
    out += stops.map(fmtStop).join('\n') + '\n\n';
    out += `**Opening-hours states:**\n`;
    out += stops.map((s,i) => `${i+1}. ${eng.stopConfidence(s.poi, result.dateStr, s.start).label}`).join('\n') + '\n\n';
    out += `**Explanations:**\n`;
    out += explanation.stopReasons.map((r,i) => `${i+1}. ${r}`).join('\n') + '\n\n';
    out += `**Summary:** ${explanation.summary}\n`;
    out += `**Trade-off note:** ${explanation.tradeOffNote || '(none)'}\n\n`;
    out += `**Cost estimate:** ${fmt.total}${fmt.food ? ` (Food: ${fmt.food}, Coffee: ${fmt.coffee}, Activities: ${fmt.activities})` : ''}\n\n`;
    out += `**Optional touches:**\n`;
    out += (touches.length ? touches.map(t => `- ${eng.formatOptionalTouch(t)}`).join('\n') : '(none available in this fixture)') + '\n\n';
    out += `---\n\n`;
  }

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, out);
  console.log(`Wrote 5 itineraries to ${OUTPUT_PATH}`);
}

main();
