#!/usr/bin/env node
'use strict';
// Generates the Sprint 3 human-readable scenario review artifact.
// Run with: node tests/generateScenarioReview.js
// Writes to: docs/validation/sprint3-scenario-review.md
//
// This script produces the ARTIFACT a human reviews. It does not assert
// anything — tests/scenario-validation.test.js is the machine-verifiable
// half; this is deliberately just a readable report generator.

const fs = require('node:fs');
const path = require('node:path');
const { loadDecisionEngine } = require('./loadDecisionEngine.js');
const { ENVIRONMENTS } = require('./fixtures/environments.js');
const { SCENARIOS } = require('./fixtures/scenarios.js');
const { runScenario, evaluateCriteria } = require('./scenarioRunner.js');

const OUTPUT_PATH = path.join(__dirname, '..', 'docs', 'validation', 'sprint3-scenario-review.md');

function fmtStop(s, i){
  const cat = s.poi.category;
  const dur = (s.end - s.start);
  const dist = s.distFromPrev != null ? s.distFromPrev.toFixed(2) + 'km' : '(first stop)';
  return `  ${i+1}. **${s.poi.tags.name}** (${cat}) — tier: \`${s.tierUsed}\`${s.relaxed ? ' (relaxed)' : ''}, ${dur}min, ${dist} from previous`;
}

function fmtChecks(checks){
  return checks.map(c => `  - [${c.pass ? 'PASS' : 'FAIL'}] ${c.name} — ${c.detail}`).join('\n');
}

function buildMatrix(){
  const envKeys = Object.keys(ENVIRONMENTS);
  const scenarioKeys = Object.keys(SCENARIOS);
  const rows = [];
  for(const scenarioKey of scenarioKeys){
    const scenario = { ...SCENARIOS[scenarioKey], __key: scenarioKey };
    const envsToRun = scenario.focusEnvironments || envKeys;
    for(const envKey of envKeys){
      if(!envsToRun.includes(envKey)) continue;
      rows.push({ envKey, scenarioKey, scenario });
    }
  }
  return rows;
}

function main(){
  const engine = loadDecisionEngine();
  const rows = buildMatrix();
  let totalChecks = 0, totalPass = 0;
  const sections = [];

  for(const { envKey, scenarioKey, scenario } of rows){
    const environment = ENVIRONMENTS[envKey];
    const result = runScenario(engine, envKey, environment, scenario);
    const checks = evaluateCriteria(engine, result);
    totalChecks += checks.length;
    totalPass += checks.filter(c=>c.pass).length;
    const allPass = checks.every(c=>c.pass);

    sections.push(`### ${environment.label} — ${scenario.label}

**Machine-verifiable result: ${allPass ? 'PASS' : 'FAIL — see below'}**

- Vibe: \`${scenario.vibe}\` · Group: \`${scenario.group}\` · Budget level: \`${scenario.budget}\` · Weather: \`${scenario.weatherKey}\` (indoorBias=${result.weather.indoorBias})
- Duration requested: ${scenario.durationHours}h (${result.startMin/60}:00–${result.endMin/60}:00)

**Resolved Day Intent Profile**
- Pace: ${result.profile.pace} · Indoor/outdoor lean: ${result.profile.indoorOutdoor} · Budget priority: ${result.profile.budgetPriority}
- Hard-excluded categories: ${Array.from(result.profile.excluded).join(', ') || '(none)'}

**Day structure**
- Density tier detected: ${result.structure.densityTier} (${result.structure.totalRelevant} relevant POIs, ${result.structure.distinctCategoriesAvailable} distinct categories nearby)
- Slot template used: [${result.structure.slotTypes.join(', ')}] · Stretch factor: ${result.structure.stretchFactor}×

**Selected stops (${result.stops.length})**
${result.stops.length ? result.stops.map(fmtStop).join('\n') : '  (none selected)'}

**Per-stop explanations**
${result.explanation ? result.explanation.stopReasons.map((r,i)=>`  ${i+1}. ${r}`).join('\n') : '  (no explanation — profile/trace unavailable)'}

**Whole-day summary:** ${result.explanation ? result.explanation.summary : '(none)'}
**Trade-off note:** ${result.explanation && result.explanation.tradeOffNote ? result.explanation.tradeOffNote : '(none — no meaningful relaxation occurred)'}

**Pass/fail against environment-specific criteria**
${fmtChecks(checks)}

**Human-review notes (judgment, not asserted by any test):**
- Does the itinerary read as one coherent day, not a list of unrelated stops? _[reviewer to fill in]_
- For village/town: does the day prioritize genuinely distinctive local character, or does it feel like generic filler? _[reviewer to fill in]_
- Does the explanation text read naturally, or does it feel templated/repetitive across stops? _[reviewer to fill in]_
`);
  }

  const header = `# Sprint 3 — Offline Scenario Validation Review

Generated by \`tests/generateScenarioReview.js\` — regenerate any time with:
\`\`\`
node tests/generateScenarioReview.js
\`\`\`

This artifact answers one question: **does DayLoop produce an acceptable day
across very different real-world environments?** It is a human-review
document, not a test report — machine-verifiable correctness is covered
separately by \`tests/scenario-validation.test.js\`. Read the two together:

1. **Machine-verifiable correctness** (below, and in the test suite): stop
   counts, tier usage, distances, hard-constraint enforcement, presence/
   absence of trade-off language, determinism. These are asserted and will
   fail CI-style if violated.
2. **Human-reviewed itinerary quality** (the "Human-review notes" under each
   scenario): whether a day actually *reads* well — narrative coherence,
   whether a village's one real landmark feels prioritized rather than
   arbitrary, whether explanation text feels natural rather than robotic.
   No automated check claims to prove these; they need an actual person to
   read the itinerary.

Environments and scenarios are defined in \`tests/fixtures/environments.js\`
and \`tests/fixtures/scenarios.js\` — both deterministic, offline, no network
calls. A documented limitation: this app has no real price/cost data source
anywhere in its pipeline, so "budget compatibility" is evaluated the same way
scorePOI evaluates it — by category (park/viewpoint/bakery/etc. lean free) —
never as an invented price figure.

**Summary: ${totalPass}/${totalChecks} machine-verifiable checks passed across ${rows.length} scenario runs.**

---

`;

  fs.writeFileSync(OUTPUT_PATH, header + sections.join('\n---\n\n'));
  console.log(`Wrote ${rows.length} scenario runs (${totalPass}/${totalChecks} checks passed) to ${OUTPUT_PATH}`);
  if(totalPass !== totalChecks){
    console.log('Some checks failed — see the artifact for details.');
    process.exitCode = 1;
  }
}

main();
